services:
  db:
    image: postgres:latest
    env_file: 
      - .env
    ports:
      - 5431:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
        build: . 
        env_file: .env
        command: #(7)
            bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; gunicorn "app:create_app()" -b 0.0.0.0:80'
        volumes: 
            - .:/flask
        ports: 
            - 8080:80

        depends_on: 
            - db
volumes:
  pgdata: