"""empty message

Revision ID: cdf637760231
Revises: cf6587210d5e
Create Date: 2023-01-26 18:03:46.331422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdf637760231'
down_revision = 'cf6587210d5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipient', schema=None) as batch_op:
        batch_op.alter_column('cpf',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=11),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipient', schema=None) as batch_op:
        batch_op.alter_column('cpf',
               existing_type=sa.String(length=11),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
